# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-thymeleaf-view-example
  labels:
    app: spring-boot-thymeleaf-view-example
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app: spring-boot-thymeleaf-view-example
  type: LoadBalancer
