name: Build and Test Java Spring Boot Application

on:
  push:
    branches:
      - main
jobs:
 build:
 steps:
 - checkout
 - run: mvn clean package
 - run: echo "BUILD SUCCESS"
test:
 steps:
 - checkout
 - run: mvn test
 - run: echo "TEST SUCCESS"
This workflow defines two jobs: `build` and `test`. The `build` job will build the Java Spring Boot application, and the `test` job will test the application.


